### ISSUE TITLE
Crash on load before KNOX key is entered

### ISSUE THREAD

**Issue by jhggygh** [LayoutXML/SABS#43]
As stated, I don't get a chance to enter my knox key before the app crashes. I had used Android Studio, much like the other issue that was closed several days ago. Using logcat I get the following error:

"03-21 16:59:22.128 13445-13509/tif.layersxmg.sabs E/com.layoutxml.sabs.dagger.module.EnterpriseModule: Failed to get firewall
                                                                                                       java.lang.NoSuchMethodError: No virtual method getFirewall()Lcom/sec/enterprise/firewall/Firewall; in class Landroid/app/enterprise/EnterpriseDeviceManager; or its super classes (declaration of 'android.app.enterprise.EnterpriseDeviceManager' appears in /system/framework/sec_edm.jar)
                                                                                                           at com.layoutxml.sabs.dagger.module.EnterpriseModule.providesFirewall(EnterpriseModule.java:101)
                                                                                                           at com.layoutxml.sabs.dagger.module.EnterpriseModule_ProvidesFirewallFactory.get(EnterpriseModule_ProvidesFirewallFactory.java:30)
                                                                                                           at com.layoutxml.sabs.dagger.module.EnterpriseModule_ProvidesFirewallFactory.get(EnterpriseModule_ProvidesFirewallFactory.java:10)
                                                                                                           at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                           at com.layoutxml.sabs.utils.AdhellAppIntegrity_MembersInjector.injectMembers(AdhellAppIntegrity_MembersInjector.java:66)
                                                                                                           at com.layoutxml.sabs.utils.AdhellAppIntegrity_MembersInjector.injectMembers(AdhellAppIntegrity_MembersInjector.java:12)
                                                                                                           at com.layoutxml.sabs.dagger.component.DaggerAppComponent.inject(DaggerAppComponent.java:314)
                                                                                                           at com.layoutxml.sabs.utils.AdhellAppIntegrity.<init>(AdhellAppIntegrity.java:67)
                                                                                                           at com.layoutxml.sabs.MainActivity.lambda$onCreate$10$MainActivity(MainActivity.java:269)
                                                                                                           at com.layoutxml.sabs.MainActivity$$Lambda$10.run(Unknown Source)
                                                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                           at java.lang.Thread.run(Thread.java:818)
03-21 16:59:22.138 13445-13509/tif.layersxmg.sabs E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                    Process: tif.layersxmg.sabs, PID: 13445
                                                                    java.lang.RuntimeException: Stub!
                                                                        at com.sec.enterprise.AppIdentity.<init>(AppIdentity.java:5)
                                                                        at com.layoutxml.sabs.utils.AdhellAppIntegrity.addDefaultAdblockWhitelist(AdhellAppIntegrity.java:213)
                                                                        at com.layoutxml.sabs.utils.AdhellAppIntegrity.check(AdhellAppIntegrity.java:95)
                                                                        at com.layoutxml.sabs.MainActivity.lambda$onCreate$10$MainActivity(MainActivity.java:270)
                                                                        at com.layoutxml.sabs.MainActivity$$Lambda$10.run(Unknown Source)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:818)"

Model: Galaxy S4 | Samsung-SGH-I337
Android Version: 5.0.1
Android Security Patch Level: 2015-11-01
KNOX 2.3

Hope this helps!

**Comment by LayoutXML** [comment]
Hi, thank you for logs. This is the same issue as #40

**Comment by LayoutXML** [comment]
@jhggygh, If I gave you a modified source code, could you try to see if it works?

**Comment by LayoutXML** [comment]
It seems like I can't fix the issue. Have you used Adhell or Adhell 2 before? If yes, did it work? I have a feeling those apps never worked on knox 2.3 as well.
